In [1]:
from ag3 import release_data
v3 = release_data()

In [2]:
import pandas as pd

In [3]:
meta_d = v3.load_sample_set_metadata(v3.all_sample_sets)

/opt/conda/lib/python3.7/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

In [10]:
meta_d["is_WGA"] = meta_d.index.map(lambda y: y.endswith("CW"))

In [13]:
pd.crosstab(meta_d["sample_set"], meta_d["is_WGA"])

is_WGA        False  True
sample_set
AG1000G-AO       81      0
AG1000G-BF-A    181      0
AG1000G-BF-B    102      0
AG1000G-BF-C     13      0
AG1000G-CD       76      0
AG1000G-CF       72      1
AG1000G-CI       80      0
AG1000G-CM-A    303      0
AG1000G-CM-B     97      0
AG1000G-CM-C     10     34
AG1000G-FR       23      0
AG1000G-GA-A     69      0
AG1000G-GH      100      0
AG1000G-GM-A     74      0
AG1000G-GM-B      0     31
AG1000G-GM-C    174      0
AG1000G-GN-A     45      0
AG1000G-GN-B    181      4
AG1000G-GQ       10      0
AG1000G-GW      101      0
AG1000G-KE       86      0
AG1000G-ML-A     53      7
AG1000G-ML-B     71      0
AG1000G-MW       41      0
AG1000G-MZ       74      0
AG1000G-TZ      299      1
AG1000G-UG      290      0
AG1000G-X       699      0

In [12]:
pd.crosstab(meta_d["sex_call"], meta_d["is_WGA"])

is_WGA    False  True
sex_call
F          2812     47
M           593      2
UKN           0     29

In [14]:
pd.crosstab(meta_d["sample_set"], meta_d["sex_call"])

sex_call        F    M  UKN
sample_set
AG1000G-AO     77    4    0
AG1000G-BF-A  151   30    0
AG1000G-BF-B   74   28    0
AG1000G-BF-C   13    0    0
AG1000G-CD     44   32    0
AG1000G-CF     73    0    0
AG1000G-CI     80    0    0
AG1000G-CM-A  258   45    0
AG1000G-CM-B   97    0    0
AG1000G-CM-C   44    0    0
AG1000G-FR     11   12    0
AG1000G-GA-A   69    0    0
AG1000G-GH    100    0    0
AG1000G-GM-A   74    0    0
AG1000G-GM-B    2    0   29
AG1000G-GM-C  174    0    0
AG1000G-GN-A   45    0    0
AG1000G-GN-B  144   41    0
AG1000G-GQ     10    0    0
AG1000G-GW    101    0    0
AG1000G-KE     75   11    0
AG1000G-ML-A   51    9    0
AG1000G-ML-B   71    0    0
AG1000G-MW     41    0    0
AG1000G-MZ     74    0    0
AG1000G-TZ    289   11    0
AG1000G-UG    290    0    0
AG1000G-X     327  372    0

In [4]:
meta_d.species_gambcolu_arabiensis.value_counts()

gamb_colu       2415
arabiensis       368
intermediate       1
Name: species_gambcolu_arabiensis, dtype: int64

In [5]:
meta_d.species_gambiae_coluzzii.value_counts()

gambiae         1571
coluzzii         675
intermediate     169
Name: species_gambiae_coluzzii, dtype: int64

In [8]:
meta_d.query("species_gambiae_coluzzii == 'intermediate'").country.value_counts()

Guinea-Bissau    72
Kenya            45
Gambia, The      41
Tanzania          7
Guinea            2
Mali              1
Burkina Faso      1
Name: country, dtype: int64

In [14]:

meta_d["species_gambcolu_arabiensis"] = pd.Categorical(meta_d.species_gambcolu_arabiensis)

In [21]:
meta_d.species_gambcolu_arabiensis.fillna("NA")

ValueError: fill value must be in categories

In [15]:
meta_d["species_gambiae_coluzzii"] = pd.Categorical(meta_d.species_gambiae_coluzzii)

In [20]:
pd.crosstab(meta_d.species_gambiae_coluzzii, meta_d.species_gambcolu_arabiensis, dropna=False)

species_gambcolu_arabiensis  arabiensis  gamb_colu  intermediate
species_gambiae_coluzzii
coluzzii                              0        675             0
gambiae                               0       1571             0
intermediate                          0        169             0